apiVersion: v1
kind: Service
metadata:
  name: message-router
  labels:
    app: message-router
    tier: backend
    component: router
  annotations:
    cloud.google.com/backend-config: '{"default": "default-backend-config"}'
    cloud.google.com/neg: '{"ingress": true}'
    cloud.google.com/load-balancer-type: "Internal"
spec:
  type: ClusterIP
  selector:
    app: message-router
  ports:
  - name: http
    port: 80
    targetPort: 8080
    protocol: TCP
  sessionAffinity: None
  sessionAffinityConfig:
    clientIP:
      timeoutSeconds: 10800
